services:
  web:
    build: .
    command: python -u manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      
    environment:
      # Force Python to be unbuffered
      - PYTHONUNBUFFERED=1

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ceapp
      POSTGRES_USER: ceapp_user
      POSTGRES_PASSWORD: ceapp_pass

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data:
