# Generated by Django 5.2.2 on 2025-06-10 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='institucion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
