# Generated by Django 5.2.2 on 2025-06-10 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0002_customuser_cargo_customuser_institucion'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('titulo', models.CharField(max_length=255)),
                ('comentarios', models.TextField()),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras_creadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('autor_creacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetivos_creados', to=settings.AUTH_USER_MODEL)),
                ('autor_modificacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetivos_modificados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BitacoraEntradaObjetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitacora_entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos_relacionados', to='ceapp.bitacoraentrada')),
                ('objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacoras_relacionadas', to='ceapp.objetivo')),
            ],
        ),
        migrations.CreateModel(
            name='PlanTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cuidador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_cuidador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='objetivo',
            name='plan_trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='ceapp.plantrabajo'),
        ),
        migrations.AddField(
            model_name='bitacoraentrada',
            name='plan_trabajo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacoras', to='ceapp.plantrabajo'),
        ),
        migrations.CreateModel(
            name='ProfesionalPlanTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesionales', to='ceapp.plantrabajo')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_profesional', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
