# Generated by Django 5.2.2 on 2025-06-12 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0003_bitacoraentrada_objetivo_bitacoraentradaobjetivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetivo',
            name='titulo',
            field=models.CharField(default='Sin titulo', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='autor_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetivos_modificados', to=settings.AUTH_USER_MODEL),
        ),
    ]
