# Generated by Django 5.2.2 on 2025-06-14 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0004_objetivo_titulo_alter_objetivo_autor_modificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetivo',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
