# Generated by Django 5.2.2 on 2025-08-24 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0005_objetivo_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaObjetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bitacoraentradaobjetivo',
            name='objetivo',
        ),
        migrations.AlterField(
            model_name='bitacoraentrada',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='profesionalplantrabajo',
            unique_together={('profesional', 'plan_trabajo')},
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='ceapp.plantrabajo')),
            ],
        ),
        migrations.CreateModel(
            name='ObjetivoEspecifico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('estado', models.IntegerField(choices=[(0, 'No logrado (NL)'), (1, 'Medianamente logrado (ML)'), (2, 'Logrado (L)')], default=0)),
                ('descripcion', models.TextField(blank=True, max_length=4000, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('autor_creacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objspe_creados', to=settings.AUTH_USER_MODEL)),
                ('autor_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objspe_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_modificacion', '-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='bitacoraentrada',
            name='objetivos_especificos',
            field=models.ManyToManyField(through='ceapp.BitacoraEntradaObjetivo', to='ceapp.objetivoespecifico'),
        ),
        migrations.AddField(
            model_name='bitacoraentradaobjetivo',
            name='objetivo_especifico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bitacoras_relacionadas', to='ceapp.objetivoespecifico'),
        ),
        migrations.CreateModel(
            name='ObjetivoGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(max_length=4000)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('autor_creacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objgen_creados', to=settings.AUTH_USER_MODEL)),
                ('autor_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objgen_modificados', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ceapp.categoriaobjetivo')),
                ('plan_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos_generales', to='ceapp.plantrabajo')),
            ],
            options={
                'ordering': ['-fecha_modificacion', '-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='objetivoespecifico',
            name='objetivo_general',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos_especificos', to='ceapp.objetivogeneral'),
        ),
        migrations.CreateModel(
            name='VinculacionObjetivoEspecifico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vinculacion', models.DateTimeField(auto_now_add=True)),
                ('objetivo_especifico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculaciones', to='ceapp.objetivoespecifico')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculaciones_objetivos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('objetivo_especifico', 'profesional')},
            },
        ),
        migrations.AddField(
            model_name='objetivoespecifico',
            name='profesionales',
            field=models.ManyToManyField(related_name='objetivos_especificos_vinculados', through='ceapp.VinculacionObjetivoEspecifico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Objetivo',
        ),
    ]
