# Generated by Django 5.2.2 on 2025-08-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceapp', '0006_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesionalplantrabajo',
            name='ultima_lectura',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
